// <auto-generated />
namespace Trabalho_MVC_Projeto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Fornecedores1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fornecedores1));
        
        string IMigrationMetadata.Id
        {
            get { return "202012032327425_Fornecedores1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
