// <auto-generated />
namespace Trabalho_MVC_Projeto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Pipa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pipa));
        
        string IMigrationMetadata.Id
        {
            get { return "202012032311117_Pipa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
